version: '2'
services:
    web:
        build: .
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
            - ./devops/apache2/vhost.conf:/etc/apache2/sites-enabled/000-default.conf
            - ./devops/php/custom.ini:/usr/local/etc/php/php.ini
        links:
            - db
    db:
        image: postgres
        ports:
            - "5432:5432"
        volumes:
            - ./devops/sql/:/root
        environment:
            POSTGRES_USER: "softexpert"
            POSTGRES_PASSWORD: "softexpert123"
            POSTGRES_DB: "test_softexpert"
